### PR TITLE
Delete package-lock.json

### PR DESCRIPTION
**Pull request by nickserv**
There's already a lockfile for pnpm

### CODE REVIEW

**Comment by delucis** [comment]
I believe this was intentional to support users regardless of their package manager. Does the extra lock file cause any issues?

**Comment by nickserv** [comment]
Yes, it can cause issues when the lockfiles become out of sync. It's especially problematic with pnpm IMO, as it has very different hoisting semantics than npm. A contributor who doesn't use pnpm may make a change that's only valid in npm and then break the project for pnpm users.

**Comment by delucis** [comment]
Got it. I wonder if actually the best solution is to not include lock files of any kind in this repo? That’s what we do for Astro starter projects.

**Comment by nickserv** [comment]
I don't think so, because then contributors and users can run into bugs caused by incorrect dependency versions. My understanding is that the Astro examples don't have lockfiles because they're in a monorepo that already has one at the root.

Though you made me realize the tutorial defaults to npm and not pnpm. Would you like a PR for that?

**Comment by binyamin** [comment]
Just chiming in:
1. **pnpm** can import **npm** and **yarn** lockfiles,, using [the `pnpm import` command](https://pnpm.io/cli/import).
2. All Astro-supported versions of Node.js ship with **corepack** ([repository](https://github.com/nodejs/corepack#readme)), which is meant to make it easy to switch between package managers.
    ```bash
    # Enable it
    corepack enable
    # Use PNPM
    corepack prepare pnpm@latest --activate
    # Or, use Yarn
    corepack prepare yarn@stable --activate
    ```

**Comment by ElianCodes** [comment]
We just upgraded our tutorial from Astro v1 to Astro v3, we're closing older PR's. If you still notice issues, you're welcome to re-submit PR's or open an issue!

**Comment by binyamin** [comment]
@ElianCodes I can confirm this is still relevant. It's an easy fix.

**Pull request closed without merging**
